name: deploy app

on:
  push:
    branches: [master]
    paths:
      - 'pages/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Builds the app for production
        run: |
          sh ./scripts/build.sh

      - name: Deploy with gh-pages for GitHub
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
          token: ${{ secrets.ACCESS_TOKEN }}
          git-config-name: Kisstar
          git-config-email: dwh.chn@foxmail.com
