name: deploy app

on:
  push:
    branches: [master]
    paths:
      - 'pages/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Set git user information
        run: |
          git config user.name $USER_NAME
          git config user.email $USER_EMAIL
        env:
          USER_NAME: kisstar
          USER_EMAIL: dwh.chn@foxmail.com

      - name: Deploy with gh-pages for GitHub
        run: |
          git remote set-url origin https://${GITHUB_TOKEN}@github.com/kisstar/${GITHUB_REPOSITORY}.git
          npx gh-pages -d pages -b gh-pages
          git remote remove origin
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GITHUB_REPOSITORY: demo
